### ISSUE TITLE
VPC subnet IP address question

### ISSUE THREAD

**Issue by Tgmertens** [ibm-cloud-docs/vmware-service#12]
What could happen with IBM Virtual Private Cloud (VPC) subnets when choosing IP ranges outside of the RFC 1918 definition (10.0.0.0/8, 172.16.0.0/12, or 192.168.0.0/16)?

A. CIDR blocks could be summarized in a single address prefix, leaving room for future growth
B. Default address prefixes won't be assigned to each zone in the region
C More IP addresses would be allocated
D. Instances attached to that subnet might be unable to reach parts of the public internet     

Any comments

**Comment by delia-rusu** [comment]
@Tgmertens can you please add the link to the topic this issue refers to?

@tlclarkibm FYI

**Comment by Tgmertens** [comment]
the question was from a test, where would i go to learn and understand IP addresses, no link available

**Comment by robw-one** [comment]
HI @Tgmertens @delia-rusu @tlclarkibm 
Please now this issue is now assigned to IBM Cloud VMware-service team though seems this is a question for IBM Cloud VPC Service.  I will provide an answer but please note as I am not on VPC team it's best not to consider this answer definitive.

--> Yes you can use IP ranges outside of the RFC 1918 in VPC and also in fact with the VMWare as a Service offering.  The warning is that if the VPC (or VMWare environment) is connected to then public internet and using subnets outside of RFC 1918 there is the danger of overlapping addresses leading to routing errors. If the VPC (or VMWare environment) is totally private and will always be private then this is fine.

**Comment by delia-rusu** [comment]
Thank you @robw-one

@Tgmertens if you'd like, you can open a doc issue for IBM Cloud Virtual Private Cloud (VPC) by using this link: https://cloud.ibm.com/docs/vpc?topic=vpc-getting-started

If you're OK with this, please close this GH issue, thanks!
